# Common--------------------------------------------------------------------------------------------
SecretId: AKIDjKirmSu7AzZyCF4e0HMEqFSTEr2D9rKY
SecretKey: 34vgDXeYHn7E1av0pRr2znMnGYgePgqo

region: ap-beijing